name: Issue new release

on:
  push:
    tags:
      - 'v*'
    branches:
      - "!*"

jobs:
  release:
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        os: [ 'ubuntu-24.04' ]
        go-version: [1.24.x]
    runs-on: ${{ matrix.os }}
    name: Release
    steps:
      - name: Set up go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true

      - name: Run GoReleaser
        if: success()
        run: |
          make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
